language: haxe

haxe:
  - "3.4.2"

env:
  - TARGET=swf
  - TARGET=as3
  - TARGET=js
  - TARGET=neko
  - TARGET=cpp
  - TARGET=cs
  - TARGET=java
  - TARGET=python

addons:
  apt:
    packages:
      - mono-devel
      - mono-mcs

install:
  - haxelib install hxcpp > /dev/null
  - haxelib install hxcs > /dev/null
  - haxelib install hxjava > /dev/null
  - haxelib list

script:
  - cd ./tests
  - haxe RunTravis.hxml
  - neko RunTravis.n $TARGET
